Repository Mulmoori/client, pull requests merged in 2024-08, with the labels that each got.

#7 ✨ Feature - Home
  src/assets/fishing-float-2.svg
  src/components/common/Badge.tsx
  src/components/common/Modal.tsx
  src/components/common/ModalInput.tsx
  src/components/home/homeRoomList/HomeRoomList.tsx
  src/components/home/homeRoomList/style.ts
  src/components/home/homeSearch/HomeSearch.tsx
  src/components/home/homeSearch/style.ts
  src/pages/home/Home.tsx
  src/pages/home/style.ts
  src/style/globalStyle.ts
  svgr.d.ts
  tsconfig.json
  vite.config.ts
Labels: 🫠 희찬, ✨ Feature

#10 Feature : Alert Modal 생성
  src/components/common/Badge.tsx
  src/components/common/Modal.tsx
  src/components/common/alert/Alert.tsx
  src/components/common/alert/style.ts
  src/components/common/badge/Badge.tsx
  src/components/common/badge/style.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalInput.tsx
  src/components/common/modal/style.ts
  src/components/home/homeRoomList/HomeRoomList.tsx
  src/components/home/homeSearch/HomeSearch.tsx
Labels: 🫠 희찬, 🔨 Refactor, ✨ Feature

#11 ✨ Feature - Dialogue STT Custom Hooks
  .github/workflows/dev_cicd.yml
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/DoubleRightChevron.svg
  src/assets/icons/Microphone.svg
  src/components/modal/dialogueDetail/DialogueDetailModal.tsx
  src/components/modal/dialogueDetail/style.ts
  src/hooks/useSpeechToText.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature

#14 🚀 Deploy - S3 Bucket Build Error Resolve
  .github/workflows/dev_cicd.yml
  tsconfig.json
Labels: 🌏 Deploy

#16 ✨ Feature - SignUp, SignIn API Connection
  package-lock.json
  package.json
  src/api/axios.ts
  src/components/auth/sign-in/sign-in-form/SignInForm.tsx
  src/components/auth/sign-up/sign-up-form/SignUpForm.tsx
  src/router.tsx
Labels: ✨ Feature

#17 ✨ Feature - Naruteo Screen(Host Mode,Participant Mode)
  .github/workflows/dev_cicd.yml
  src/assets/icons/Microphone.svg
  src/assets/icons/MicrophoneIcon.tsx
  src/components/layouts/Navbart.tsx
  src/components/modal/dialogueDetail/DialogueDetailModal.tsx
  src/components/modal/dialogueDetail/style.ts
  src/components/naruteo/header/header.tsx
  src/components/naruteo/header/style.ts
  src/components/naruteo/questionBoxList/questionBox/questionBox.tsx
  src/components/naruteo/questionBoxList/questionBox/style.ts
  src/components/naruteo/questionBoxList/questionBoxList.tsx
  src/components/naruteo/questionBoxList/style.ts
  src/components/naruteo/tabBar/style.ts
  src/components/naruteo/tabBar/tabBar.tsx
  src/components/naruteo/tag/style.ts
  src/components/naruteo/tag/tag.tsx
  src/pages/naruteo/Naruteo.tsx
  src/pages/naruteo/style.ts
  src/pages/room/Room.tsx
  src/router.tsx
Labels: 😇 현정, ✨ Feature

#19 ✨ Feature - Profile Page API Connection
  src/pages/profile/Profile.tsx
Labels: ✨ Feature

#22 ✨ Feature - Narooteo API Connection - 1
  src/api/axios.ts
  src/assets/icons/CopyButton.svg
  src/components/common/modal/ModalInput.tsx
  src/components/home/homeSearch/HomeSearch.tsx
  src/components/naruteo/header/header.tsx
  src/components/naruteo/header/style.ts
  src/components/naruteo/tabBar/tabBar.tsx
  src/context/narooteoState.ts
  src/main.tsx
  src/pages/naruteo/Naruteo.tsx
  src/router.tsx
  src/utils/DateTimeUtils.ts
Labels: 🥹 창섭, ✨ Feature
